//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerService.IServerService")]
    public interface IServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Multiplication", ReplyAction="http://tempuri.org/IServerService/MultiplicationResponse")]
        int Multiplication(int[] Matrix1, int[] Matrix2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Multiplication", ReplyAction="http://tempuri.org/IServerService/MultiplicationResponse")]
        System.Threading.Tasks.Task<int> MultiplicationAsync(int[] Matrix1, int[] Matrix2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerServiceChannel : WindowsFormsApplication1.ServerService.IServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerServiceClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServerService.IServerService>, WindowsFormsApplication1.ServerService.IServerService {
        
        public ServerServiceClient() {
        }
        
        public ServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Multiplication(int[] Matrix1, int[] Matrix2) {
            return base.Channel.Multiplication(Matrix1, Matrix2);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicationAsync(int[] Matrix1, int[] Matrix2) {
            return base.Channel.MultiplicationAsync(Matrix1, Matrix2);
        }
    }
}
